services:
  oba_bundler:
    build:
      context: ./bundler
      args:
        - PAT_USERNAME_FOR_GH=${PAT_USERNAME_FOR_GH}
        - PAT_TOKEN_FOR_GH=${PAT_TOKEN_FOR_GH}
    volumes:
      - ./bundle:/bundle
    environment:
      - GTFS_URL

  oba_database:
    image: mysql:8.4
    container_name: oba_database
    environment:
      MYSQL_ROOT_PASSWORD: Ins3cure!
      MYSQL_DATABASE: oba_database
      MYSQL_USER: oba_user
      MYSQL_PASSWORD: oba_password
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    restart: always

  oba_app:
    container_name: oba_app
    depends_on:
      - oba_database
    build:
      context: ./oba
      args:
        - PAT_USERNAME_FOR_GH=${PAT_USERNAME_FOR_GH}
        - PAT_TOKEN_FOR_GH=${PAT_TOKEN_FOR_GH}
    environment:
      - JDBC_URL=jdbc:mysql://oba_database:3306/oba_database
      - JDBC_USER=oba_user
      - JDBC_PASSWORD=oba_password
      - TEST_API_KEY=test # For test only, remove in production
      - TZ=America/Los_Angeles

    volumes:
      # Share the host's `bundle` directory
      # with the filesystem of the OBA service.
      - ./bundle:/bundle
    ports:
      # Access the webapp on your host machine at a path like
      # http://localhost:8080/onebusaway-api-webapp/api/where/agency/${YOUR_AGENCY}.json?key=TEST
      - "8080:8080"
    # restart: always

volumes:
  mysql-data:
